language: perl
before_install:
  - perlbrew -f install-cpanm
  - cpanm -n git://github.com/kan/coveralls-perl.git
script: perl Build.PL && ./Build && ./Build testcover
after_success:
  - cover -report coveralls
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

